### ISSUE TITLE
Create Comprehensive Observability for Patient Service

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#31]
# Implementing Comprehensive Observability for Patient Service

## Background
To better understand our patient service's behavior, performance, and health in production, we need to implement a comprehensive observability solution. This initiative will combine logs, metrics, and traces to provide a complete view of our system's operation.

### Log Management with Fluent Bit and Loki
We'll start by implementing structured logging using Fluent Bit as our log forwarder and Loki as our log storage. Fluent Bit will collect logs from our containers and forward them to Loki, providing a centralized logging solution.

The Fluent Bit configuration listens for logs on port 24224 and forwards them to Grafana Loki:
```ini
[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224
[Output]
    Name grafana-loki
    Match *
    Url ${LOKI_URL}
```

This setup enables structured logging with labels, making it easier to query and analyze logs based on container names and other metadata.

### Metrics Collection with Prometheus
For metrics collection, we're configuring Prometheus to scrape our patient service endpoints every 2 seconds:
```yaml
global:
  scrape_interval: 2s
scrape_configs:
  - job_name: 'patient-service'
    metrics_path: '/actuator/prometheus'
```

To support this, we need to update our application's actuator endpoints and expose build information:

1. Update application.yml:
```yaml
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
```

2. Enable build info in build.gradle.kts:
```groovy
springBoot {
    buildInfo()
}
```

### Distributed Tracing with Tempo
We're implementing distributed tracing using Tempo, which will help us understand request flows through our system:
```yaml
server:
  http_listen_port: 3100
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
```

### Visualization with Grafana
The entire observability stack comes together in Grafana, where we're setting up:
- Custom dashboards for patient service metrics
- Log exploration through Loki
- Trace visualization via Tempo

### Infrastructure as Code
All components are defined in our docker-compose.yml, ensuring consistent deployment:
```yaml
services:
  loki:
    image: grafana/loki:2.9.8
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.9.8
  prometheus:
    image: quay.io/prometheus/prometheus:v2.52.0
```

## Expected Benefits
1. Enhanced Debugging: Quick identification of issues through correlated logs, metrics, and traces
2. Improved Performance Monitoring: Real-time metrics and dashboards
3. Better System Understanding: Complete visibility into request flows and system behavior

## Implementation Steps
1. Deploy logging infrastructure (Fluent Bit + Loki)
2. Configure Prometheus for metrics collection
3. Set up Tempo for distributed tracing
4. Configure Grafana dashboards
5. Update application configurations
6. Verify data collection and visualization

## Success Criteria
- [ ] Logs are successfully forwarded to Loki
- [ ] Metrics are being collected by Prometheus
- [ ] Traces are captured in Tempo
- [ ] Grafana dashboards show meaningful data
- [ ] Teams can effectively use the tools for troubleshooting

Would you like me to elaborate on any of these components or provide more technical details about their implementation?

Create a Fluent Bit file
https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter13/13-end/polar-deployment/docker/observability/fluent-bit/fluent-bit.conf

```ini
[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224
[Output]
    Name grafana-loki
    Match *
    Url ${LOKI_URL}
    RemoveKeys source,container_id
    Labels {job="fluent-bit"}
    LabelKeys container_name
    BatchWait 1s
    BatchSize 1001024
    LineFormat json
    LogLevel info
```

Grafana Dashboards
https://github.com/ThomasVitale/cloud-native-spring-in-action/tree/main/Chapter13/13-end/polar-deployment/docker/observability/grafana/dashboards

Grafana Datasource
https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter13/13-end/polar-deployment/docker/observability/grafana/datasources/datasource.yml

Grafana ini
https://github.com/ThomasVitale/cloud-native-spring-in-action/tree/main/Chapter13/13-end/polar-deployment/docker/observability/grafana

Prometheus
```yml
global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'patient-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'patient-service:9020' ]
```

Temp
```yml
server:
  http_listen_port: 3100

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

usage_report:
  reporting_enabled: false
```

Docker-compose
```yml
loki:
    image: grafana/loki:2.9.8
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.9.8
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  prometheus:
    image: quay.io/prometheus/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: -config.file=/etc/tempo-config.yml
    ports:
      - "3110:3100"     # Tempo
      - "4317:4317"     # OTel
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo-config.yml
```
  

Update the actuator
https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter13/13-end/catalog-service/src/main/java/com/polarbookshop/catalogservice/config/SecurityConfig.java#L21

Update application properties
https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter13/13-end/catalog-service/src/main/resources/application.yml#L55

Expose build information
https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter13/13-end/catalog-service/build.gradle#L61

Expose OS information
https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter13/13-end/catalog-service/src/main/resources/application.yml#L63
