### ISSUE TITLE
Create Deployment Directory

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#9]
# User Story: Centralized Docker Compose Configuration

## Title
As a DevOps engineer, I need a centralized docker-compose.yml file that references all service Dockerfiles in the general-hospital system.

## Description
Create a single docker-compose.yml in the deployment directory that manages all services, with each service maintaining its own Dockerfile in its respective directory.

### Directory Structure
```
general-hospital/
├── deployment/
│   ├── docker-compose.yml        # Single compose file for all services
├── patient-service/
│   └── Dockerfile               # Patient service Dockerfile
├── appointment-service/
│   └── Dockerfile               # Appointment service Dockerfile
└── gateway-service/
    └── Dockerfile               # Gateway service Dockerfile
```

### Centralized Docker Compose Configuration
```yaml
# deployment/docker-compose.yml
version: '3.8'

services:
  patient-service:
    build:
      context: ../patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "8001:8001"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - general-hospital-network

networks:
  general-hospital-network:
    name: general-hospital-network
```

### Implementation Steps

Create Core Files:
```bash
touch general-hospital/deployment/docker-compose.yml
```

## Definition of Done
- [x] Single docker-compose.yml created in deployment directory
- [x] All services properly referenced from their respective directories
- [x] Environment templates configured
- [x] Network settings defined
- [x] Documentation completed
- [x] Successfully tested local deployment
